Support g2o viewer build on windows
paul-michalik/g2o pull request #8
Opened 2018-03-02 09:14 UTC by PTavse

2018-03-02 09:54 UTC, paul-michalik commented
Why reopen an already merged pull request? Please create a new one from a branch created for the purpose of the task

2018-03-02 14:53 UTC, paul-michalik requested changes

2018-03-02 14:53 UTC, paul-michalik commented on scripts/windows/bootstrap.bat
> +rem ==============================
```
rem 
rem ... if it does not exist already...?
rem 
set "QGLViewerPath=%~dp0..\..\Thirdparty\libQGLViewer-2.7.1\"
set "QGLVIEWERROOT=%QGLViewerPath%\QGLViewer" 
if not exists "%QGLVIEWERROOT%\QGLViewer2.dll" (
    rem all the statements below...
)
```

2018-03-02 14:53 UTC, paul-michalik commented on scripts/windows/bootstrap.bat
> +rem ==============================
Maybe even factor out to a separate script e.g. `bootstrap-ogl-viewer.bat` and invoke 
```
call "%~dp0bootstrap-ogl-viewer.bat"
```

2018-03-05 05:48 UTC, PTavse commented
I guess i branched the code before these pull requests were merged. If I am not wrong i would have to rebase the branch? 
About the QGLViewer build, there could be two ways to provide the libraries:
1) Download and build the code while building g2o code as i did in the first commit.
2) We can just directly make the libraries available in "Thirdparty" folder and just set QGLVIEWERROOT to the path to Thirdparty folder, as ansuman suggested.
Which one would you suggest?

2018-03-05 07:38 UTC, paul-michalik commented
No, you have branched several days after the pull request were merged. What I don't understand is where you have branched from. You should have branched from master at `24db3a771df48fe26192e433504f4829597b97f2` but I don't see that commit at all. Strange, we need to get rid of this.

I'd prefer 1. possibility. Only this guarantees consistency across all dependencies...

2018-03-05 12:36 UTC, closed without merging